### ISSUE TITLE
Reorganization suggestion

### ISSUE THREAD

**Issue by Req** [JodieDiaz/LifeCoach#1]
Hi! Looks like we were both working on the same project at the same time :) You did a really great starting point and I wanted to make some change suggestions to it.

Our versions are both public
- https://req.github.io/LifeCoach/ 
- https://life-coach-sand.vercel.app/ 

Sadly, I don't think I can rebase my work onto yours, the differences of us working at the sane time are simply too big. There are 11 commits that are missing from my branch while I was working.

So, since you are the actual designer, I would like to ask you what you want to do :smiley: I see three main options;

A) You have a look at my version and decide if you want to take some changes from there, making the changes yourself
B) You take my version and remake your new changes on top of my work.
C) We don't use anything from my version and just publish yours

Which do you prefer? Or do you have another suggestion? In _any_ case I would recommend looking at the Chrome Lighthouse reports for mobile in your devtools.

In any case, I think we can publish the first version at any time. Did you already have a hosting provider in mind?

P.S. If you are interested in more specific feedback (not really a code review, but just some random thoughts) I wrote some stuff to https://github.com/Req/LifeCoach/blob/alt/Notes.md

**Comment by JodieDiaz** [comment]
Hello Joel! Thank you very much for your valuable contribution. I learned a lot, especially about using GitHub more effectively.

I really liked how you improved the page structure with its components and how the header and footer turned out just as I wanted them to be. You're really good at this!

Finally, I took your version and adjusted the image transparency to my liking while trying to adhere to the contrast rule you mentioned. I also changed the image format to webP and made some style changes.

I used the Lighthouse tool, and I found it fantastic for measuring the page's performance. Thanks for that tip; I'm still learning.

Regarding the page's hosting, I was thinking of hosting it on Hostinger, but if you have recommendations for other hosting providers, I'd appreciate it if you could share more information with me.

![WhatsApp Image 2023-09-23 at 1 19 27 AM](https://github.com/JodieDiaz/LifeCoach/assets/113044626/40b7bedc-2aec-45a7-835f-991c665222c7)

Gracias totales.

**Comment by Req** [comment]
Those are some really nice Lighthouse numbers! :) 

For hosting, because this is a purely static site that doesn't need PHP or Node or anything, I was actually thinking of using a free CloudFlare Pages project for this. I don't think the page should hit the traffic limit of the free tier, and it would be globally fast. You could set up a CF project and invite me and Dafne. What do you think?

The reason for the invites is just to have "backup" people; if we need to quickly change the domain or something, Dafne or I could do it (at least that's how I hope the CF projects work :smile: ) 

I think Dafne mentioned she already has a domain, do you have access to the DNS? Setting up CF is basically instant and  we could just do the DNS

**Comment by Req** [comment]
Hey :) I was wondering if I can help with anything for the deployment / hosting? 

For the hosting, what would you think is the price of Hostinger with servers close to Finland? If it's low cost, that's a totally fine option too

**Comment by JodieDiaz** [comment]
**Hello Joel, :) I apologize, I've been very busy with a new e-commerce project.

I believe I've managed to transfer the DNS from Godaddy to CloudFlare. It's great that it's free, that way it's better for Dafne since she's just starting out.

I have several questions about how to publish the page, can it be done from GitHub? How can I add you and Dafne to the project? I really appreciate your willingness to help.**

Wishing you a wonderful day.

<img width="1353" alt="Captura de Pantalla 2023-10-02 a la(s) 12 39 47 p m" src="https://github.com/JodieDiaz/LifeCoach/assets/113044626/3a75761b-b2da-4259-bd1f-69999921a5f3">

**Comment by JodieDiaz** [comment]
"Hello again!

I wanted to inform you that I've made significant progress with the CF project and have created and published Dafne's website with the domain psic-finlandia.com. Furthermore, I've already added Dafne to the project. Now, all that's left is your invitation so you can also access the project and have access to the configuration, as you mentioned.

To send you the invitation, I need your email address associated with your CloudFlare account. Could you please provide it? Once I have it, I'll send you the invitation, and you'll be able to join the project.

Thanks in advance for your cooperation!"

<img width="1129" alt="Captura de Pantalla 2023-10-03 a la(s) 11 14 20 a m" src="https://github.com/JodieDiaz/LifeCoach/assets/113044626/61de16f5-0d26-43d1-b8b7-baf3dbe3d53a">

**Comment by Req** [comment]
Oooh, nice work! The page loads fast too :rocket: 

I'm joel.peltonen@digitalcareerinstitute.org :)

**Comment by Req** [comment]
Closing this :) it was fun!
